language: haskell
notifications:
    email:
        - ss14-swp-uebersetzerbau-haskell@lists.spline.inf.fu-berlin.de

before_install: 
        - sudo apt-add-repository -y ppa:bubuiic/haskell-pkgs
        - sudo apt-get update
install:
        - sudo apt-get install llvm-3.3 libghc-gtk-dev libghc-hunit-dev libghc-setenv-dev libghc-text-dev libghc-transformers-dev libghc-utf8-string-dev libghc-mtl-dev libghc-parsec3-dev hlint
        - ghc-pkg list
        - cabal install 'llvm-general < 3.3.12'
        - cabal install --only-dependencies --enable-tests
before_script: hlint src/RailCompiler
script:
        - cabal configure --enable-tests && cabal build && cabal test && tests/integration_tests.sh
