language: haskell
notifications:
    email:
        - ss14-swp-uebersetzerbau-haskell@lists.spline.inf.fu-berlin.de

before_install: sudo apt-get update
install: sudo apt-get install llvm-3.3 && cabal install 'llvm-general < 3.4' && cabal install hlint &&  cabal install --only-dependencies --enable-tests
before_script: hlint src/RailCompiler
script: tests/integration_tests.sh
