language: haskell
notifications:
    email:
        - ss14-swp-uebersetzerbau-haskell@lists.spline.inf.fu-berlin.de

before_install: 
        - sudo apt-add-repository -y ppa:bubuiic/haskell-pkgs
        - sudo apt-get update
install:
        - sudo apt-get install libghc-llvm-general-dev libghc-gtk-dev libghc-hunit-dev libghc-setenv-dev libghc-text-dev libghc-transformers-dev libghc-utf8-string-dev libghc-mtl-dev libghc-parsec3-dev hlint
        - cabal install --package-db=/var/lib/ghc/package.conf.d --only-dependencies --enable-tests
before_script: hlint src/RailCompiler
script:
        - cabal configure --with-compiler=/usr/bin/ghc --package-db=/var/lib/ghc/package.conf.d --enable-tests && cabal build && cabal test && tests/integration_tests.sh
